Repository AllAlgorithms/python, pull requests merged in 2020-10, with the labels that each got.

#61 Added a stack data structure
  data-structures/stack/stack.py
Labels: bug, invalid, on hold

#58 Added stack to data structures and unitary tests
  data-structures/stacks/node.py
  data-structures/stacks/stack.py
  data-structures/stacks/test_node.py
  data-structures/stacks/test_stack.py
Labels: on hold

#49 Coin change problem in recursive way.
  recursion/Coin-Change-Problem.py
Labels: bad format
